//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accidents
    {
        public int id_accident { get; set; }
        public Nullable<int> id_personnel { get; set; }
        public Nullable<int> id_vehicule { get; set; }
        public Nullable<System.DateTime> date_saisie { get; set; }
        public Nullable<int> id_type_suivi { get; set; }
        public Nullable<int> id_detail_accident { get; set; }
        public Nullable<int> id_doc { get; set; }
        public string path_document { get; set; }
    
        public virtual Details_Accidents Details_Accidents { get; set; }
        public virtual Vehicules Vehicules { get; set; }
    }
}
