//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Affectations
    {
        public int id_affectation { get; set; }
        public Nullable<System.DateTime> date_du { get; set; }
        public Nullable<System.DateTime> date_au { get; set; }
        public Nullable<int> id_personnel { get; set; }
        public Nullable<int> id_vehicule { get; set; }
        public Nullable<int> id_equipe { get; set; }
        public Nullable<int> id_equipement { get; set; }
        public string chef_equipe { get; set; }
        public string type_affecte { get; set; }
        public Nullable<int> id_texte { get; set; }
    
        public virtual Vehicules Vehicules { get; set; }
        public virtual Equipements Equipements { get; set; }
    }
}
