//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Controles_Vehicules
    {
        public int id_controle { get; set; }
        public int id_vehicule { get; set; }
        public Nullable<System.DateTime> date_obtention { get; set; }
        public string organisme { get; set; }
        public Nullable<double> cout { get; set; }
        public Nullable<System.DateTime> date_recyclage { get; set; }
        public string organisme_recyclage { get; set; }
        public Nullable<double> cout_recyclage { get; set; }
        public string description { get; set; }
        public Nullable<int> tri { get; set; }
        public Nullable<int> id_valeur_liste { get; set; }
    
        public virtual Vehicules Vehicules { get; set; }
    }
}
