//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Details_Accidents
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Details_Accidents()
        {
            this.Accidents = new HashSet<Accidents>();
            this.Suivis_Medicals = new HashSet<Suivis_Medicals>();
        }
    
        public int id_detail_accident { get; set; }
        public string jour_semaine { get; set; }
        public Nullable<System.DateTime> date_accident { get; set; }
        public string heure { get; set; }
        public string horraire_jour { get; set; }
        public string lieu { get; set; }
        public string circonstances { get; set; }
        public string siege_lesions { get; set; }
        public string nature_lesions { get; set; }
        public string hopital { get; set; }
        public Nullable<int> id_consequences_accident { get; set; }
        public Nullable<int> id_temoin { get; set; }
        public string temoins { get; set; }
        public string rapport_police { get; set; }
        public string cause_tiers { get; set; }
        public string nom_tiers { get; set; }
        public string arret_travail { get; set; }
        public string assurance_tiers { get; set; }
        public Nullable<int> id_type_constat_accident { get; set; }
        public Nullable<System.DateTime> date_constat { get; set; }
        public string heure_constat { get; set; }
        public string constat_employeur { get; set; }
        public string constat_preposes { get; set; }
        public string constat_victime { get; set; }
        public string numero { get; set; }
        public string rapport_parqui { get; set; }
        public string autre_victime { get; set; }
        public Nullable<int> id_vehicule { get; set; }
        public string activite { get; set; }
        public string path_document { get; set; }
    
        public virtual Vehicules Vehicules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Accidents> Accidents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Suivis_Medicals> Suivis_Medicals { get; set; }
    }
}
