//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doc_Lignes_Four
    {
        public int id_ligne { get; set; }
        public Nullable<int> id_doc { get; set; }
        public Nullable<int> id_vehicule { get; set; }
        public Nullable<int> id_famille { get; set; }
        public string description { get; set; }
        public Nullable<double> quantite { get; set; }
        public Nullable<double> prix_unitaire { get; set; }
        public Nullable<double> montant { get; set; }
        public Nullable<int> id_equipement { get; set; }
        public Nullable<System.DateTime> date_du { get; set; }
        public Nullable<System.DateTime> date_au { get; set; }
        public Nullable<int> kilometre { get; set; }
        public Nullable<int> kilometres_parcourus { get; set; }
        public Nullable<int> id_personnel { get; set; }
    
        public virtual Vehicules Vehicules { get; set; }
        public virtual Doc_Entete_Four Doc_Entete_Four { get; set; }
        public virtual Equipements Equipements { get; set; }
    }
}
