//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doc_Entete_Four
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doc_Entete_Four()
        {
            this.Doc_Lignes_Four = new HashSet<Doc_Lignes_Four>();
        }
    
        public int id_doc { get; set; }
        public Nullable<int> numero { get; set; }
        public string reference_doc { get; set; }
        public string description { get; set; }
        public Nullable<int> id_fournisseur { get; set; }
        public Nullable<System.DateTime> date_doc { get; set; }
        public Nullable<double> montant_ht { get; set; }
        public Nullable<int> id_utilisateur { get; set; }
        public Nullable<int> id_type_intervention { get; set; }
        public string type_depense { get; set; }
        public Nullable<double> montant_MO { get; set; }
        public string type_prix { get; set; }
    
        public virtual Fournisseurs Fournisseurs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Doc_Lignes_Four> Doc_Lignes_Four { get; set; }
    }
}
