//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipements
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipements()
        {
            this.Affectations = new HashSet<Affectations>();
            this.Doc_Lignes_Four = new HashSet<Doc_Lignes_Four>();
        }
    
        public int id_equipement { get; set; }
        public string reference { get; set; }
        public string designation { get; set; }
        public string num_serie { get; set; }
        public string marque { get; set; }
        public string caractéristique { get; set; }
        public string modele { get; set; }
        public Nullable<int> id_famille_equipement { get; set; }
        public string actif { get; set; }
        public string equipe_tempo { get; set; }
        public Nullable<System.DateTime> date_achat { get; set; }
        public Nullable<double> prix_acquisition { get; set; }
        public string etat { get; set; }
        public Nullable<int> id_fournisseur { get; set; }
        public Nullable<int> id_controleur { get; set; }
        public Nullable<System.DateTime> date_limite { get; set; }
        public string photo { get; set; }
        public Nullable<int> id_societe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Affectations> Affectations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Doc_Lignes_Four> Doc_Lignes_Four { get; set; }
        public virtual Fournisseurs Fournisseurs { get; set; }
    }
}
