//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fournisseurs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fournisseurs()
        {
            this.Doc_Entete_Four = new HashSet<Doc_Entete_Four>();
            this.Equipements = new HashSet<Equipements>();
        }
    
        public int id_fournisseur { get; set; }
        public string code_fournisseur { get; set; }
        public string nom { get; set; }
        public string adresse1 { get; set; }
        public string adresse2 { get; set; }
        public string code_postal { get; set; }
        public string ville { get; set; }
        public string telephone1 { get; set; }
        public string telecopie { get; set; }
        public string pays { get; set; }
        public string contact { get; set; }
        public string telephone2 { get; set; }
        public string email { get; set; }
        public Nullable<int> import { get; set; }
        public Nullable<int> carte { get; set; }
        public string compte_client { get; set; }
        public string actif { get; set; }
        public string compte_auxiliaire { get; set; }
        public string compte_collectif { get; set; }
        public Nullable<int> id_famille_fournisseur { get; set; }
        public string OKCarburant { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Doc_Entete_Four> Doc_Entete_Four { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equipements> Equipements { get; set; }
    }
}
