//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restrictions_Medicales
    {
        public int id_restriction { get; set; }
        public Nullable<int> id_suivi_medical { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> date_du { get; set; }
        public Nullable<System.DateTime> date_au { get; set; }
        public Nullable<int> id_personnel { get; set; }
    
        public virtual Suivis_Medicals Suivis_Medicals { get; set; }
    }
}
