//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suivis_Medicals
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Suivis_Medicals()
        {
            this.Restrictions_Medicales = new HashSet<Restrictions_Medicales>();
        }
    
        public int id_suivi_medical { get; set; }
        public Nullable<int> id_personnel { get; set; }
        public Nullable<int> id_type_suivi { get; set; }
        public Nullable<System.DateTime> date_arret { get; set; }
        public Nullable<System.DateTime> date_reprise { get; set; }
        public Nullable<int> nbjour_arret { get; set; }
        public Nullable<System.DateTime> date_visite { get; set; }
        public Nullable<System.DateTime> date_renou { get; set; }
        public string nature_lesion { get; set; }
        public string siege_lesion { get; set; }
        public string cause { get; set; }
        public string cote_lesion { get; set; }
        public Nullable<int> id_accident { get; set; }
        public string restrictions { get; set; }
        public string lesions { get; set; }
        public string explication { get; set; }
        public Nullable<int> nbjour_arret_ouvres { get; set; }
    
        public virtual Details_Accidents Details_Accidents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Restrictions_Medicales> Restrictions_Medicales { get; set; }
    }
}
