//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicules
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicules()
        {
            this.Affectations = new HashSet<Affectations>();
            this.Controles_Vehicules = new HashSet<Controles_Vehicules>();
            this.Details_Accidents = new HashSet<Details_Accidents>();
            this.Doc_Lignes_Four = new HashSet<Doc_Lignes_Four>();
            this.Vehicules_Compteurs = new HashSet<Vehicules_Compteurs>();
            this.Accidents = new HashSet<Accidents>();
        }
    
        public int id_vehicule { get; set; }
        public string num_interne { get; set; }
        public string Designation { get; set; }
        public string immat { get; set; }
        public string Num_serie { get; set; }
        public Nullable<int> compteur_heure { get; set; }
        public Nullable<int> compteur_KM { get; set; }
        public Nullable<System.DateTime> date_compteur { get; set; }
        public Nullable<System.DateTime> date_heure { get; set; }
        public string marque { get; set; }
        public string caracteristique { get; set; }
        public string modele { get; set; }
        public string num_analystique { get; set; }
        public Nullable<int> id_famille_vehicule { get; set; }
        public string actif { get; set; }
        public string telephone { get; set; }
        public Nullable<System.DateTime> dateEntree { get; set; }
        public string photo { get; set; }
        public Nullable<double> valeur_acquisition { get; set; }
        public string num_facture { get; set; }
        public string location { get; set; }
        public Nullable<System.DateTime> date_sortie { get; set; }
        public Nullable<int> id_societe { get; set; }
    
        public virtual Familles_Vehicules Familles_Vehicules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Affectations> Affectations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Controles_Vehicules> Controles_Vehicules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Details_Accidents> Details_Accidents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Doc_Lignes_Four> Doc_Lignes_Four { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vehicules_Compteurs> Vehicules_Compteurs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Accidents> Accidents { get; set; }
    }
}
