//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SAGA_GASQUETEntities : DbContext
    {
        public SAGA_GASQUETEntities()
            : base("name=SAGA_GASQUETEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Familles_Vehicules> Familles_Vehicules { get; set; }
        public virtual DbSet<Vehicules> Vehicules { get; set; }
        public virtual DbSet<Affectations> Affectations { get; set; }
        public virtual DbSet<Controles_Vehicules> Controles_Vehicules { get; set; }
        public virtual DbSet<Details_Accidents> Details_Accidents { get; set; }
        public virtual DbSet<Doc_Lignes_Four> Doc_Lignes_Four { get; set; }
        public virtual DbSet<Vehicules_Compteurs> Vehicules_Compteurs { get; set; }
        public virtual DbSet<Accidents> Accidents { get; set; }
        public virtual DbSet<Suivis_Medicals> Suivis_Medicals { get; set; }
        public virtual DbSet<Restrictions_Medicales> Restrictions_Medicales { get; set; }
        public virtual DbSet<Doc_Entete_Four> Doc_Entete_Four { get; set; }
        public virtual DbSet<Fournisseurs> Fournisseurs { get; set; }
        public virtual DbSet<Equipements> Equipements { get; set; }
    }
}
