//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicules_Compteurs
    {
        public int id_compteur { get; set; }
        public int id_vehicule { get; set; }
        public string type_compteur { get; set; }
        public Nullable<System.DateTime> date_compteur { get; set; }
        public Nullable<long> val_compteur { get; set; }
    
        public virtual Vehicules Vehicules { get; set; }
    }
}
